---
services:
    ubuntu:
        build: .
        container_name: ubuntu-container
        ports:
        - "8080:80"
        expose:
        - "3306"
        networks:
            custom_network:
                ipv4_address: 172.69.0.10


networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.69.0.0/24"
