services:
    mariadb:
        image: mariadb:latest
        container_name: dolibarr_db_sae_cambonsahuc
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-dolidb}
            MYSQL_USER: ${MYSQL_USER:-dolidbuser}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-dolidbpass}
        volumes:
            - ./dolibarr_mariadb:/var/lib/mysql

    web:
        image: dolibarr/dolibarr:20.0.0
        container_name: dolibarr_web_sae_cambonsahuc
        environment:
            WWW_USER_ID: ${WWW_USER_ID:-1000}
            WWW_GROUP_ID: ${WWW_GROUP_ID:-1000}
            DOLI_DB_HOST: ${DOLI_DB_HOST:-mariadb}
            DOLI_DB_NAME: ${DOLI_DB_NAME:-dolidb}
            DOLI_DB_USER: ${DOLI_DB_USER:-dolidbuser}
            DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD:-dolidbpass}
            DOLI_URL_ROOT: "${DOLI_URL_ROOT}"
            DOLI_ADMIN_LOGIN: "${DOLI_ADMIN_LOGIN}"
            DOLI_ADMIN_PASSWORD: "${DOLI_ADMIN_PASSWORD}"
            DOLI_CRON: ${DOLI_CRON:-0}
            DOLI_INIT_DEMO: ${DOLI_INIT_DEMO}
            DOLI_COMPANY_NAME: ${DOLI_COMPANY_NAME}
        ports:
            - "80:80"
        links:
            - mariadb
        volumes:
            - ../backups:/backups
            - ../imports:/root/csv_import