services:
    mariadb:
        image: mariadb:latest
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: dolibarr


    web:
        image: dolibarr/dolibarr:latest
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
            DOLI_ADMIN_LOGIN: 'admin'
            DOLI_ADMIN_PASSWORD: 'admin'
            DOLI_INIT_DEMO: 0
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "80:80"
        links:
            - mariadb


    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
        ports:
        - 8080:8080